from __future__ import absolute_import, division, print_function

__metaclass__ = type


# This is hardcoded, the response is from DataPower v 10.0.1.0.
# This could be greatly improved by having it check at the beginning
# of module execution
def is_valid_class(class_name):
    return class_name in valid_objects


class DPActionQueue():
    def __init__(self, **kwargs):
        for k,v in kwargs.items():
            setattr(self, k, v)


class DPGetConfigObject:
    def __init__(self, **kwargs):
        for k,v in kwargs.items():
            setattr(self, k, v)


class DPManageConfigObject:
    # domain and class_name are the bare minimum required to get a valid
    # response from DataPower
    # kwargs consisting of the arguments defined in the Ansible Modules
    def __init__(self, **kwargs):
        for k,v in kwargs.items():
            setattr(self, k, v)
        
        # Try to set class_name, the module allows for some flexibility
        # it can be set by specifying it as class_name
        # or within the config dictionary
        if not hasattr(self, 'class_name') or self.class_name is None:
            self.class_name = list(self.config.keys())[0]
            if not is_valid_class(self.class_name):
                raise ValueError('Invalid class_name or no class_name provided.')
        
        # Try to set name, the module allows for some flexibility
        # it can be set by specifying it as name
        # or within the config dictionary
        if not hasattr(self, 'name') or self.name is None:
            if self.class_name in self.config:
                self.name = self.config.get(self.class_name).get('name')
            elif 'name' in self.config:
                self.name = self.config.get('name')
            else:
                raise AttributeError('name attribute is required.')




valid_objects = [ 
    'AAAPolicy',
    'Domain',
    'LDAPSearchParameters',
    'ProcessingMetadata',
    'RADIUSSettings',
    'RBMSettings',
    'SAMLAttributes',
    'SOAPHeaderDisposition',
    'TAM',
    'TFIMEndpoint',
    'XACMLPDP',
    'AccessControlList',
    'AccessProfile',
    'AnalyticsEndpoint',
    'APIApplicationType',
    'APICollection',
    'APIConnectGatewayService',
    'APIDefinition',
    'APIGateway',
    'APILDAPRegistry',
    'APIOperation',
    'APIPath',
    'APIPlan',
    'APISchema',
    'APISecurityAPIKey',
    'APISecurityBasicAuth',
    'APISecurityOAuthReq',
    'APISecurityOAuth',
    'APISecurityRequirement',
    'APISecurityTokenManager',
    'AppSecurityPolicy',
    'Assembly',
    'AuditLog',
    'B2BCPA',
    'B2BCPACollaboration',
    'B2BCPAReceiverSetting',
    'B2BCPASenderSetting',
    'B2BGateway',
    'B2BPersistence',
    'B2BProfile',
    'B2BProfileGroup',
    'B2BXPathRoutingPolicy',
    'WXSGrid',
    'XC10Grid',
    'CloudConnectorService',
    'CloudGatewayService',
    'CompactFlash',
    'CompileOptionsPolicy',
    'ConfigDeploymentPolicy',
    'ConfigSequence',
    'ConformancePolicy',
    'ControlList',
    'AAAJWTGenerator',
    'AAAJWTValidator',
    'CertMonitor',
    'CookieAttributePolicy',
    'CRLFetch',
    'CryptoCertificate',
    'CryptoFWCred',
    'CryptoIdentCred',
    'CryptoKerberosKDC',
    'CryptoKerberosKeytab',
    'CryptoKey',
    'CryptoProfile',
    'CryptoSSKey',
    'CryptoValCred',
    'JOSERecipientIdentifier',
    'JOSESignatureIdentifier',
    'JWEHeader',
    'JWERecipient',
    'JWSSignature',
    'OAuthSupportedClient',
    'OAuthSupportedClientGroup',
    'SocialLoginPolicy',
    'SSHClientProfile',
    'SSHDomainClientProfile',
    'SSHServerProfile',
    'SSLClientProfile',
    'SSLProxyProfile',
    'SSLServerProfile',
    'SSLSNIMapping',
    'SSLSNIServerProfile',
    'DeploymentPolicyParametersBinding',
    'ErrorReportSettings',
    'SystemSettings',
    'TimeSettings',
    'DFDLSettings',
    'DomainAvailability',
    'DomainSettings',
    'SchemaExceptionMap',
    'DocumentCryptoMap',
    'XPathRoutingMap',
    'LogTarget',
    'FormsLoginPolicy',
    'FTPQuoteCommands',
    'MultiProtocolGateway',
    'WSGateway',
    'GatewayPeering',
    'GeneratedPolicy',
    'GWScriptSettings',
    'HTTPInputConversionMap',
    'HTTPUserAgent',
    'ILMTScanner',
    'ImportPackage',
    'IMSConnect',
    'IncludeConfig',
    'InteropService',
    'EthernetInterface',
    'LinkAggregation',
    'VLANInterface',
    'IPMILanChannel',
    'IPMIUser',
    'IPMulticast',
    'ISAMReverseProxy',
    'ISAMReverseProxyJunction',
    'ISAMRuntime',
    'IScsiChapConfig',
    'IScsiHBAConfig',
    'IScsiInitiatorConfig',
    'IScsiTargetConfig',
    'IScsiVolumeConfig',
    'TibcoEMSServer',
    'WebSphereJMSServer',
    'JSONSettings',
    'Language',
    'LDAPConnectionPool',
    'LoadBalancerGroup',
    'LogLabel',
    'Luna',
    'LunaPartition',
    'Matching',
    'MCFCustomRule',
    'MCFHttpHeader',
    'MCFHttpMethod',
    'MCFHttpURL',
    'MCFXPath',
    'MessageContentFilters',
    'FilterAction',
    'MessageMatching',
    'CountMonitor',
    'DurationMonitor',
    'MessageType',
    'MPGWErrorAction',
    'MPGWErrorHandlingPolicy',
    'MQGW',
    'MQhost',
    'MQproxy',
    'MQQM',
    'MQQMGroup',
    'MTOMPolicy',
    'NameValueProfile',
    'DNSNameService',
    'HostAlias',
    'NetworkSettings',
    'NTPService',
    'NFSClientSettings',
    'NFSDynamicMounts',
    'NFSStaticMount',
    'OAuthProviderSettings',
    'ODR',
    'ODRConnectorGroup',
    'OperationRateLimit',
    'ParseSettings',
    'PasswordAlias',
    'Pattern',
    'PeerGroup',
    'PolicyAttachments',
    'PolicyParameters',
    'ProductInsights',
    'QuotaEnforcementServer',
    'RaidVolume',
    'SQLRuntimeSettings',
    'SecureBackupMode',
    'SecureCloudConnector',
    'SecureGatewayClient',
    'GWSRemoteDebug',
    'MgmtInterface',
    'RestMgmtInterface',
    'SSHService',
    'TelnetService',
    'WebB2BViewer',
    'WebGUI',
    'XMLFirewallService',
    'XSLProxyService',
    'HTTPService',
    'SSLProxyService',
    'TCPProxyService',
    'XSLCoprocService',
    'ShellAlias',
    'SimpleCountMonitor',
    'SLMAction',
    'SLMCredClass',
    'SLMPolicy',
    'SLMRsrcClass',
    'SLMSchedule',
    'SMTPServerConnection',
    'SNMPSettings',
    'AS2ProxySourceProtocolHandler',
    'AS2SourceProtocolHandler',
    'AS3SourceProtocolHandler',
    'EBMS2SourceProtocolHandler',
    'EBMS3SourceProtocolHandler',
    'FTPFilePollerSourceProtocolHandler',
    'NFSFilePollerSourceProtocolHandler',
    'SFTPFilePollerSourceProtocolHandler',
    'FTPServerSourceProtocolHandler',
    'HTTPSourceProtocolHandler',
    'HTTPSSourceProtocolHandler',
    'IMSCalloutSourceProtocolHandler',
    'IMSConnectSourceProtocolHandler',
    'TibcoEMSSourceProtocolHandler',
    'WebSphereJMSSourceProtocolHandler',
    'MQFTESourceProtocolHandler',
    'MQSourceProtocolHandler',
    'AS1PollerSourceProtocolHandler',
    'POPPollerSourceProtocolHandler',
    'SSHServerSourceProtocolHandler',
    'StatelessTCPSourceProtocolHandler',
    'XTCProtocolHandler',
    'SQLDataSource',
    'StandaloneStandbyControl',
    'StandaloneStandbyControlInterface',
    'Statistics',
    'StylePolicy',
    'APIClientIdentification',
    'APIContext',
    'APICORS',
    'APIExecute',
    'APIRateLimit',
    'APIResult',
    'APIRouting',
    'APISecurity',
    'AssemblyActionGatewayScript',
    'AssemblyActionInvoke',
    'AssemblyActionJson2Xml',
    'AssemblyActionJWTGenerate',
    'AssemblyActionJWTValidate',
    'AssemblyActionMap',
    'AssemblyActionOAuth',
    'AssemblyActionParse',
    'AssemblyActionSetVar',
    'AssemblyActionUserSecurity',
    'AssemblyActionValidate',
    'AssemblyActionXml2Json',
    'AssemblyActionXSLT',
    'AssemblyActionThrow',
    'AssemblyLogicSwitch',
    'StylePolicyAction',
    'APIRule',
    'StylePolicyRule',
    'WSStylePolicyRule',
    'Tenant',
    'Throttler',
    'UDDIRegistry',
    'URLMap',
    'URLRefreshPolicy',
    'URLRewritePolicy',
    'User',
    'UserGroup',
    'WCCService',
    'WebAppErrorHandlingPolicy',
    'WebAppFW',
    'WebAppRequest',
    'WebAppResponse',
    'WebAppSessionPolicy',
    'WebServiceMonitor',
    'WebServicesAgent',
    'UDDISubscription',
    'WSRRSavedSearchSubscription',
    'WSRRSubscription',
    'WebTokenService',
    'WSEndpointRewritePolicy',
    'WSRRServer',
    'WSStylePolicy',
    'XMLManager',
    'xmltrace',
    'ZHybridTargetControlService',
    'ZosNSSClient',
]
