FROM ibmcom/datapower:{{ version }}
ENV DATAPOWER_ACCEPT_LICENSE="true" 
ENV DATAPOWER_INTERACTIVE="true" 
EXPOSE 9090
EXPOSE 5554
EXPOSE 8443
{% if '2018' in version -%}
COPY $PWD/config /drouter/config
USER root
RUN chown -R drouter:drouter /drouter/config 
{%- else -%}
COPY $PWD/config /opt/ibm/datapower/drouter/config
USER root
RUN chown -R drouter:drouter /opt/ibm/datapower/drouter/config
{%- endif %}

RUN set-user drouter
USER drouter